name: Build (Tier 2 platforms with flaky builds)

# FreeBSD build via vmactions/freebsd-vm is known to fail randomly,
# so we don't want it to be triggered on every commit.

# Manually triggered
on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo


jobs:

  freebsd:
    runs-on: ubuntu-latest
#    env:
#    variables to pass to VM
#    MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4

    - name: Build and test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'BUILD_TYPE'
        usesh: true
        sync: rsync
        # release: "14.0"
        prepare: >
          pkg install -y cmake pkgconf gtkmm30 gettext libiconv

        run: >
          mkdir build && cd build

          cmake ..
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DAPP_BUILD_EXAMPLES=ON
          -DAPP_BUILD_TESTS=ON
          -DAPP_COMPILER_ENABLE_WARNINGS=ON

          cmake --build . --config $BUILD_TYPE

          ctest -C $BUILD_TYPE --rerun-failed --output-on-failure
